import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(resolve(root, "index.html"), "utf8");
const css = readFileSync(resolve(root, "styles.css"), "utf8");
const js = readFileSync(resolve(root, "app.js"), "utf8");

for (const localAsset of ["styles.css", "app.js"]) {
  assert.ok(existsSync(resolve(root, localAsset)), `${localAsset} exists`);
  assert.ok(html.includes(localAsset), `${localAsset} is referenced`);
}
assert.ok(existsSync(resolve(root, "forstaff.png")), "forstaff.png exists");

assert.ok(html.includes("役員報酬検討ツール"));
assert.ok(html.includes("役員報酬を中心に"));
assert.ok(!html.includes("松本会計 実務補助ツール"));
assert.ok(html.includes("v1.20"));
assert.ok(html.includes("forstaff.png"));
assert.ok(html.includes("rel=\"icon\""));
assert.ok(html.includes("rel=\"shortcut icon\""));
assert.ok(html.includes("rel=\"apple-touch-icon\""));
assert.ok(html.includes("app-footer"));
assert.ok(html.includes("panel-note"));
assert.ok(html.includes("section-heading"));
assert.ok(html.includes("section-index"));
assert.ok(html.includes("会社・役員の前提"));
assert.ok(html.includes("現在の役員報酬月額"));
assert.ok(html.includes("現在の役員A月額"));
assert.ok(html.includes("現在の役員B月額"));
assert.ok(html.includes("会社側"));
assert.ok(html.includes("単独役員の報酬"));
assert.ok(html.includes("夫婦役員の報酬"));
assert.ok(html.includes("探索幅"));
assert.ok(html.includes("その他所得"));
assert.ok(!html.includes("持株・その他所得"));
assert.ok(html.includes("詳細設定：税率・社会保険料率"));
assert.ok(html.includes("使い方"));
assert.ok(html.includes("id=\"printPage\""));
assert.ok(html.includes("印刷"));
assert.ok(html.includes("manualDialog"));
assert.ok(html.includes("strategyPreset"));
assert.ok(html.includes("内部留保から逆算"));
assert.ok(html.indexOf('value="retainedTarget"') < html.indexOf('value="balanced"'));
assert.ok(html.includes("roleMode"));
assert.ok(html.includes("class=\"field-subhead field-full couple-only\" hidden"));
assert.ok(html.includes("class=\"field couple-only couple-split-only\""));
assert.ok(html.includes("class=\"field couple-only couple-grid-only\""));
assert.ok(html.includes("class=\"field-subhead field-full single-only\""));
assert.ok(html.includes("夫婦役員：合計報酬を固定して配分"));
assert.ok(html.includes("夫婦役員：A/Bそれぞれを探索"));
assert.ok(html.includes("夫婦合計月額報酬"));
assert.ok(html.includes("役員Aの探索上限"));
assert.ok(html.includes("役員Bの探索上限"));
assert.ok(html.includes("stepLabel"));
assert.ok(html.includes("職務執行の対価"));
assert.ok(html.includes("役員Bの持株割合"));
assert.ok(html.includes("役員Bの報酬に社会保険をかける"));
assert.ok(html.includes("バランス型"));
assert.ok(html.includes("目標法人留保"));
assert.ok(html.includes("目標留保"));
assert.ok(html.includes("target-retained-field"));
assert.ok(html.includes('class="field field-full target-retained-field" for="targetRetained">'));
assert.ok(html.indexOf('id="targetRetained"') < html.indexOf('id="taxYear"'));
assert.ok(html.includes("法人留保目標に近い案"));
assert.ok(html.includes("法人資金温存"));
assert.ok(html.includes("配当を考慮する（オプション）"));
assert.ok(html.includes('id="includeDividend"'));
assert.ok(html.includes("dividend-option-field"));
assert.ok(html.includes("dividend-share-grid"));
assert.ok(html.indexOf('id="shareRate"') > html.indexOf('id="includeDividend"'));
assert.ok(html.includes("持株割合は配当受取額の按分にだけ使用します"));
assert.ok(html.includes("カスタム：手動調整中"));
assert.ok(html.includes("社会保険加入状況"));
assert.ok(html.includes("協会けんぽ支部"));
assert.ok(html.includes("全国一律です"));
assert.ok(html.includes("北海道 10.28%"));
assert.ok(html.includes("兵庫 10.12%"));
assert.ok(html.includes("佐賀 10.55%"));
assert.ok(html.includes("手入力"));
assert.ok(html.includes("法人留保"));
assert.ok(html.includes("上位30件をコピー"));
assert.ok(html.includes("全候補をダウンロード"));
assert.doesNotMatch(html, /type=["']range["']/i);
assert.doesNotMatch(html, /data-for=/i);
assert.ok(html.includes("value=\"50,000\""));
assert.ok(html.includes("配当控除 所得税 (課税所得1,000万円以下部分)"));
assert.ok(html.includes("配当控除 所得税 (課税所得1,000万円超部分)"));
assert.ok(html.includes("配当控除 住民税 (課税所得1,000万円以下部分)"));
assert.ok(html.includes("配当控除 住民税 (課税所得1,000万円超部分)"));
assert.ok(html.includes("令和8・9年分"));
assert.ok(html.includes("令和10年分以後"));
assert.ok(html.includes("国民健康保険料・国民年金保険料"));
assert.ok(html.includes("CPI連動見直し"));
assert.ok(html.includes("令和8年度の都道府県別料率"));
assert.ok(js.includes("renderBalance"));
assert.ok(js.includes("simulateCoupleSplit"));
assert.ok(js.includes("simulateCoupleGrid"));
assert.ok(js.includes("simulatePeople"));
assert.ok(js.includes("primaryPerson"));
assert.ok(js.includes("spousePerson"));
assert.ok(js.includes("持株割合合計が100%を超えています"));
assert.ok(js.includes("役員A月額の刻み幅"));
assert.ok(js.includes("A/B月額の刻み幅"));
assert.ok(js.includes("presetControlledIds"));
assert.ok(js.includes("markStrategyCustom"));
assert.ok(js.includes("bestByMonthlyBucket"));
assert.ok(js.includes("monthlyBucketLabel"));
assert.ok(js.includes("latestRows = rows"));
assert.ok(js.includes("latestRows.slice(0, 30)"));
assert.ok(js.includes("row.retained"));
assert.ok(js.includes("measureText"));
assert.ok(js.includes("renderRecommendationReason"));
assert.ok(js.includes("renderTargetReasonVisual"));
assert.ok(js.includes("現在の役員報酬月額との比較"));
assert.ok(js.includes("renderReasonBreakdownChart"));
assert.ok(js.includes("targetVisualData"));
assert.ok(js.includes("retainedTarget"));
assert.ok(js.includes("targetRetained"));
assert.ok(js.includes("retainedGap"));
assert.ok(js.includes("compareRows"));
assert.ok(js.includes("目標法人留保"));
assert.ok(js.includes("drawChart(rows, current, p)"));
assert.ok(js.includes("ctx.setLineDash([6, 6])"));
assert.ok(js.includes("目標留保"));
assert.ok(js.includes("前利益 ${man(p.preProfit)}"));
assert.ok(js.includes("持株割合"));
assert.ok(js.includes("他の株主"));
assert.ok(js.includes("strategyPresets"));
assert.ok(js.includes("applyStrategyPreset"));
assert.ok(js.includes("updateDependentControls"));
assert.ok(js.includes("includeDividend"));
assert.ok(js.includes("if(!p.includeDividend) return [0]"));
assert.ok(js.includes("const ownerRetainedValue = retained"));
assert.ok(!js.includes("retained * householdShare"));
assert.ok(js.includes('renderTable(rows, p)'));
assert.ok(js.includes('renderBalance(best, current, p)'));
assert.ok(js.includes('targetField.hidden = objective !== "retainedTarget"'));
assert.ok(!js.includes("syncAllRangesFromInputs"));
assert.ok(js.includes("prefectureRates"));
assert.ok(js.includes("getPrefectureRate"));
assert.ok(js.includes("applyPrefectureRate"));
assert.ok(js.includes("markPrefectureCustom"));
assert.ok(js.includes("bindManualDialog"));
assert.ok(js.includes("window.print"));
assert.ok(js.includes('querySelectorAll(".couple-only")'));
assert.ok(js.includes('querySelectorAll(".single-only")'));
assert.ok(js.includes("el.hidden = !coupleMode"));
assert.ok(js.includes("el.hidden = coupleMode"));
assert.ok(js.includes("formatMoneyLive"));
assert.ok(js.includes("createCalculator"));
assert.ok(js.includes("1040000"));
assert.ok(js.includes("990000"));
assert.ok(css.includes(".balance-track"));
assert.ok(css.includes(".legend-dot.retained"));
assert.ok(css.includes(".legend-dot.target"));
assert.ok(css.includes(".recommendation-reason"));
assert.ok(css.includes(".reason-list"));
assert.ok(css.includes(".reason-target-track"));
assert.ok(css.includes(".reason-comparison-flow"));
assert.ok(css.includes(".reason-comparison-point"));
assert.ok(css.includes(".reason-breakdown-track"));
assert.ok(css.includes(".reason-formulas"));
assert.ok(css.includes(".header-actions"));
assert.ok(css.includes(".brand-logo"));
assert.ok(css.includes(".app-footer"));
assert.ok(css.includes("font-size:clamp(18px,2.2vw,24px)"));
assert.ok(css.includes("@media print"));
assert.ok(css.includes(".no-print"));
assert.ok(css.includes("[hidden]"));
assert.ok(css.includes("display:none!important"));
assert.ok(css.includes(".panel-note"));
assert.ok(css.includes(".section-heading"));
assert.ok(css.includes(".section-index"));
assert.ok(css.includes(".summary-index"));
assert.ok(css.includes(".field-subhead"));
assert.ok(css.includes(".field-note"));
assert.ok(css.includes(".split-amount"));
assert.ok(css.includes(".manual-dialog"));
assert.ok(css.includes(".manual-steps"));
assert.ok(!html.includes("比較月額"));
assert.ok(!js.includes("比較月額"));
assert.ok(!css.includes(".reason-gap-row"));
assert.doesNotMatch(html, /<script[^>]+src=["']https?:/i);
assert.doesNotMatch(html, /<link[^>]+href=["']https?:/i);

console.log("Build check passed.");
